name: UltimateAntiBot
version: ${project.version}
main: me.kr1s_d.ultimateantibot.UltimateAntiBotSpigot
api-version: 1.21
folia-supported: true
authors: [ Kr1S_D ]
description: Another antibot plugin!
load: STARTUP
commands:
  ultimateantibot:
    aliases: [ab, uab]